name: Develop Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Meadow.Modbus
      uses: actions/checkout@v3
      with:
        path: Meadow.Modbus
        ref: main
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Build Meadow.Modbus
      run: dotnet build -c Release Meadow.Modbus/src/Meadow.Modbus.sln
